### ISSUE TITLE
Missing decency on pywin32

### ISSUE THREAD

**Issue by vidartf** [conda-forge/jupyter_client-feedstock#29]
In https://github.com/jupyter/jupyter_client/pull/469, a platform dependent dependency was added on pywin32. This dependency does not seem to have made it into the conda forge package, as reported here: https://github.com/jupyterlab/jupyterlab/issues/7259

**Comment by jasongrout** [comment]
CC owen-synergy, who filed the original issue in JuptyerLab.

**Comment by msbuckas** [comment]
Hi - I'm still getting the error when starting JupyterLab (as per the original post) for WIndows x64.

I have done a **_conda update --all_**  and have the ffg. in my env:
 
 Name                    Version                   Build  Channel
jupyter_client            5.3.3                      py_0
jupyter_core              4.5.0                      py_0
jupyterlab                1.1.3              pyhf63ae98_0
jupyterlab_server         1.0.6                      py_0

Do I have to wait for a new _**jupyter_client**_ version to get this fix?

**Comment by jasongrout** [comment]
The fix is in the most current jupyter_client on conda-forge. It did change from a noarch package to an arch-specific package which may complicate things?

Can you try explicitly updating jupyter_client? The correct packages have build 1: https://anaconda.org/conda-forge/jupyter_client/files

**Comment by msbuckas** [comment]
@jasongrout  I got the direct download to work.

Yes, I think the -noarch to -win64 was a complication, therefore:
1. conda remove jupyter_client (this also removed jupyterlab)
2. conda install --offline "C:\<mydir>\jupyter_client-5.3.3-py37_1.tar.bz2"
3. conda  install jupyterlab

NB! I first tried just step2 - but it did not fix the prob. So it looks like the -noarch pkg must be removed before the -win64 pkg gets installed? And step3 may also subsequently install other dependencies because of this hack?

Thanks for your quick help!

**Comment by jasongrout** [comment]
You should be able to remove just the jupyter_client package with `conda remove jupyter_client --force` or something.

**Comment by msbuckas** [comment]
This issue is 'Closed' so I assume no further work is being done to resolve the arising -noarch vs -win64 packaging complication? Surely, the workaround is a temporary hack and users are not indefinately required to remove -noarch jupyter_client and then download and install the -win64 jupyter_client?

**Comment by jasongrout** [comment]
As a follow-up, pywin32 was removed as a dependency in jupyter_client 6.0, so I think this is no longer an issue: https://github.com/jupyter/jupyter_client/blob/1a25d7ddb1e68aef3ae3aeef87058c0a7a2daf0d/CHANGELOG.md#600
